table 'e-commerce customers'
	lineageTag: 5ca8a533-be8a-4ec5-acf8-270e68ad073c

	measure 'Total Customers' = DISTINCTCOUNT('e-commerce customers'[customer_unique_id])
		formatString: 0
		lineageTag: 4fdbcb76-5b67-48b3-93fb-cf4d87089d87

	column customer_id
		dataType: string
		lineageTag: def09a51-caa0-49fb-bd25-399a8abaf5ea
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: ef611d9c-dddb-49ec-941c-9f1c004f01c4
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: string
		lineageTag: f90dd481-c939-4ce8-9d80-3ae7f81d4ac7
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 28ee983c-367a-493d-a0e3-b4dcfcc7b02a
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 146b5017-2b95-43c7-b4a1-370a7a6277ca
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column 'Orders Per Customer' =
			
			CALCULATE(
			    COUNT('e-commerce orders'[order_id]),
			    ALLEXCEPT('e-commerce customers', 'e-commerce customers'[customer_unique_id])
			)
		formatString: 0
		lineageTag: 281fd926-9a04-4d9d-af00-353b6507b1c3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Purchase Category' =
			
			IF(
			'e-commerce customers'[Orders Per Customer] = 1,
			"One-Time Purchase",
			"Repeat Purchase"
			)
		lineageTag: 9067da79-549a-4316-be9f-cda8d69a6812
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce customers' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_customers" = Source{[Schema="e-commerce",Item="customers"]}[Data]
				in
				    #"e-commerce_customers"

	annotation PBI_ResultType = Table

