table 'e-commerce product_category_name_translation'
	lineageTag: df1d661a-3385-4161-97b0-78cfd5bfa63b

	column product_category_name
		dataType: string
		lineageTag: 20942de0-1100-4a1f-891d-a2bfc03aa8fb
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_category_name_english
		dataType: string
		lineageTag: 3009e91b-c0bb-4094-a795-f353851dc77f
		summarizeBy: none
		sourceColumn: product_category_name_english

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce product_category_name_translation' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_product_category_name_translation" = Source{[Schema="e-commerce",Item="product_category_name_translation"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(#"e-commerce_product_category_name_translation","_"," ",Replacer.ReplaceText,{"product_category_name_english"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Replaced Value",{{"product_category_name_english", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

