table 'e-commerce leads_closed'
	lineageTag: 594ac898-d6e9-4c02-a772-4d73f862f1e6

	column mql_id_id
		dataType: string
		lineageTag: e7a11fa7-da7d-4bdf-a27a-73f4e12c8f18
		summarizeBy: none
		sourceColumn: mql_id_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 49535e44-cf5e-4792-8caa-33775d37287d
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column sdr_id
		dataType: string
		lineageTag: e1f24685-1dff-471c-9feb-357998cbf699
		summarizeBy: none
		sourceColumn: sdr_id

		annotation SummarizationSetBy = Automatic

	column sr_id
		dataType: string
		lineageTag: 490b7d36-4d12-4228-a45f-b6695b1fdaa7
		summarizeBy: none
		sourceColumn: sr_id

		annotation SummarizationSetBy = Automatic

	column won_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c8096177-cfb0-4d53-a8f0-3e6f800e8cd8
		summarizeBy: none
		sourceColumn: won_date

		variation Variation
			isDefault
			relationship: fb9b0633-cfcc-4c92-ae23-ba5b882dd2b1
			defaultHierarchy: LocalDateTable_81b0596a-8429-448f-a624-de195e4be9d9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column business_segment
		dataType: string
		lineageTag: 480cd4b8-38cf-43fa-a95a-3a6e0184b5da
		summarizeBy: none
		sourceColumn: business_segment

		annotation SummarizationSetBy = Automatic

	column lead_type
		dataType: string
		lineageTag: 50bcbae7-a5d1-456a-b430-d4472ae242e5
		summarizeBy: none
		sourceColumn: lead_type

		annotation SummarizationSetBy = Automatic

	column lead_behaviour_profile
		dataType: string
		lineageTag: cf930973-6daa-40b3-ad04-3e1b6cbe30c5
		summarizeBy: none
		sourceColumn: lead_behaviour_profile

		annotation SummarizationSetBy = Automatic

	column has_company
		dataType: string
		lineageTag: 84843cd2-84d1-475e-90ab-b096967c143d
		summarizeBy: none
		sourceColumn: has_company

		annotation SummarizationSetBy = Automatic

	column has_gtin
		dataType: string
		lineageTag: db6f505b-0b77-4b3d-b535-9ef3f1948d43
		summarizeBy: none
		sourceColumn: has_gtin

		annotation SummarizationSetBy = Automatic

	column average_stock
		dataType: string
		lineageTag: e93930b7-5ab6-487c-821f-a78ffbe09e3b
		summarizeBy: none
		sourceColumn: average_stock

		annotation SummarizationSetBy = Automatic

	column business_type
		dataType: string
		lineageTag: d10e91be-c778-41df-9206-e308f36f912b
		summarizeBy: none
		sourceColumn: business_type

		annotation SummarizationSetBy = Automatic

	column declared_product_catalog_size
		dataType: string
		lineageTag: df11226f-a349-4c0b-861d-e58391ce4ebe
		summarizeBy: none
		sourceColumn: declared_product_catalog_size

		annotation SummarizationSetBy = Automatic

	column declared_monthly_revenue
		dataType: int64
		formatString: 0
		lineageTag: 199f8778-6f83-4fc4-a466-fba293db4d26
		summarizeBy: sum
		sourceColumn: declared_monthly_revenue

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce leads_closed' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_leads_closed" = Source{[Schema="e-commerce",Item="leads_closed"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(#"e-commerce_leads_closed",{{"lead_type", Text.Proper, type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","","Other",Replacer.ReplaceValue,{"lead_type"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Other","Others",Replacer.ReplaceText,{"lead_type"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","_"," ",Replacer.ReplaceText,{"lead_type"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value2", each true),
				    #"Replaced Value3" = Table.ReplaceValue(#"Filtered Rows","","other",Replacer.ReplaceValue,{"business_type"}),
				    #"Capitalized Each Word1" = Table.TransformColumns(#"Replaced Value3",{{"business_type", Text.Proper, type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Capitalized Each Word1", each true),
				    #"Replaced Value4" = Table.ReplaceValue(#"Filtered Rows1","Other","Others",Replacer.ReplaceText,{"business_type"})
				in
				    #"Replaced Value4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

