table 'e-commerce lead_conversion'
	lineageTag: da2c78a0-5f24-4891-b225-595b504c7c19

	column origin
		dataType: string
		lineageTag: 057b9276-79f0-4297-b7a2-45f726fbd7ac
		summarizeBy: none
		sourceColumn: origin

		annotation SummarizationSetBy = Automatic

	column qualified_leads
		dataType: int64
		formatString: 0
		lineageTag: b4c6aa65-be8b-49c3-a558-052075d53c4a
		summarizeBy: none
		sourceColumn: qualified_leads

		annotation SummarizationSetBy = Automatic

	column closed_leads
		dataType: int64
		formatString: 0
		lineageTag: 34d25aae-94e9-4c85-8f88-dad3ad65f25b
		summarizeBy: none
		sourceColumn: closed_leads

		annotation SummarizationSetBy = Automatic

	column conversion_rate
		dataType: double
		lineageTag: 927ad7af-1de9-4178-bc01-f158d6d633fd
		summarizeBy: none
		sourceColumn: conversion_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'e-commerce lead_conversion' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_lead_conversion" = Source{[Schema="e-commerce",Item="lead_conversion"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(#"e-commerce_lead_conversion",{{"origin", Text.Proper, type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","_"," ",Replacer.ReplaceText,{"origin"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

