table 'e-commerce orders'
	lineageTag: df0f1fa9-7c8e-4c10-bf61-aad3289b01c8

	measure 'Delivery Performance (Average Shipping Duration (Days))' = ```
			
			VAR AvgDeliveryDays = 
			    AVERAGEX(
			        FILTER(
			            'e-commerce orders',
			            -- 1. Ensure the order was delivered (or check the order_status)
			            NOT ISBLANK('e-commerce orders'[order_delivered_customer_date])),
			        -- 2. Check if both dates are present before calculating the difference
			        IF(
			            AND(
			                NOT ISBLANK('e-commerce orders'[order_delivered_carrier_date]),
			                NOT ISBLANK('e-commerce orders'[order_delivered_customer_date])
			            ),
			            'e-commerce orders'[order_delivered_customer_date] - 'e-commerce orders'[order_delivered_carrier_date],
			            BLANK()))
			
			RETURN
			    -- Format the numerical result (e.g., 5.45) to include the word "days".
			    -- "0.00" ensures the result is shown with two decimal places.
			    FORMAT(AvgDeliveryDays, "0.00 \d\a\y\s")
			```
		lineageTag: c3d2fc4d-20e8-4467-9129-c696fec207d0

	measure 'Total Orders' = DISTINCTCOUNT('e-commerce orders'[order_id])
		formatString: 0
		lineageTag: e656cb5a-d20b-4af4-a13e-08fbf05e433c

	measure 'Processing Performance (Hrs)' = ```
			
			VAR AvgProcessingTime =
			    AVERAGEX(
			        FILTER(
			            'e-commerce orders',
			            NOT ISBLANK('e-commerce orders'[order_purchase_timestamp])),
			            IF(
			                AND(
			                    NOT ISBLANK('e-commerce orders'[order_purchase_timestamp]),
			                    NOT ISBLANK('e-commerce orders'[order_approved_at])
			                ),
			                'e-commerce orders'[order_approved_at] - 'e-commerce orders'[order_purchase_timestamp],
			                BLANK()))
			RETURN
			    -- format the numerical result (e.g., 5.45) to include the word "days".
			    -- "0.00" ensures the result is shown with two decimal places.
			    FORMAT(AvgProcessingTime, "0.00 \H\r\s")
			
			```
		lineageTag: 5bb83b24-9510-4ab3-826b-b5064917c43a

	measure 'Average Shipping to Carriers' =
			
			VAR AvgShippingCarriers =
			    AVERAGEX(
			        FILTER(
			            'e-commerce orders',
			            NOT ISBLANK('e-commerce orders'[order_approved_at])),
			        IF(
			            AND(
			                NOT ISBLANK('e-commerce orders'[order_delivered_carrier_date]),
			                NOT ISBLANK('e-commerce orders'[order_approved_at])),
			                'e-commerce orders'[order_delivered_carrier_date] - 'e-commerce orders'[order_approved_at],
			                BLANK()))
			RETURN
			    -- format the numerical result (e.g., 5.45) to include the word "days".
			    -- "0.00" ensures the result is shown with two decimal places.
			    FORMAT(AvgShippingCarriers, "0.00 \d\a\y\s")
		lineageTag: 58f98867-a479-4607-a24a-f53587d4579a

	measure 'Delivery Variance (Actual vs. Estimate) (Days)' = ```
			
			VAR AvgDeliveryDays =
			    AVERAGEX(
			        -- ARGUMENT 1: Filtered Table (Only look at orders with customer delivery dates)
			        FILTER(
			            'e-commerce orders',
			            NOT ISBLANK('e-commerce orders'[order_delivered_customer_date])
			        ),
			        -- ARGUMENT 2: The Expression to Average (The date difference calculation)
			        -- Check if both estimated and actual dates are present before calculating the difference
			        IF(
			            AND(
			                NOT ISBLANK('e-commerce orders'[order_estimated_delivery_date]),
			                NOT ISBLANK('e-commerce orders'[order_delivered_customer_date])
			            ),
			            'e-commerce orders'[order_estimated_delivery_date] - 'e-commerce orders'[order_delivered_customer_date],
			            BLANK()
			        )
			    )
			RETURN
			    AvgDeliveryDays
			
			```
		lineageTag: fac26707-3def-4ae2-a5fc-3607ee7c9de9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: string
		lineageTag: 727b018c-2519-43f4-b109-8dab6263a1fb
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 29acecd2-1966-432d-92cb-8eb3e03c72b7
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: b8c9211c-12c8-4760-b152-bb7d9bd5821a
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 3aeeff56-2ccb-4280-86c2-eeb01dbea311
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: 730cfc65-5a4d-4b64-b0e2-25177c0ccc2d
			defaultHierarchy: LocalDateTable_713359a8-6e39-4f9a-ae52-7947c68a58ce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 6691ba50-2599-4b1c-990b-08d5b63a26b9
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: 9851adc6-e3d9-4ab5-bc52-652cf062031e
			defaultHierarchy: LocalDateTable_aaa1e6d5-5b06-442a-a292-1cfcc8089199.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9462f695-0e0e-48ca-af85-7378244b1afb
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 41e98ecc-aacf-47c2-8fd6-aea7b337a774
			defaultHierarchy: LocalDateTable_5e4ea146-9fd5-4156-9f30-5ab2ec775245.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d7339cec-b165-49d1-8a5f-ab92fda13ed5
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 7a66653b-01c5-4b6b-9ed5-6468842d9f5a
			defaultHierarchy: LocalDateTable_b8742f48-5642-421b-8cd2-9d12ec23fed8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 23f02831-c13b-4734-bff4-09e6b0cc25ea
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: bc0a50fb-bb44-4c7b-b148-2e4ca3135eee
			defaultHierarchy: LocalDateTable_e686ea7b-ac9b-41f6-b782-4c2adb6711a0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short' = FORMAT('e-commerce orders'[order_estimated_delivery_date], "mmm")
		lineageTag: 9dbe9f25-f9bd-42a6-8935-edb2ac0546f1
		summarizeBy: none
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Number' = MONTH('e-commerce orders'[order_estimated_delivery_date])
		formatString: 0
		lineageTag: cd425bc2-cb44-47ff-80bb-228c0f024a8b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Delivery Status Group' = ```
			
			VAR DeliveryDifference = 'e-commerce orders'[order_delivered_customer_date] - 'e-commerce orders'[order_estimated_delivery_date]
			        
			RETURN
			    IF(
			        ISBLANK('e-commerce orders'[order_delivered_customer_date]),
			        "Not Delivered",
			        SWITCH(
			            TRUE(),
			            DeliveryDifference < -7, "Very Early",           -- More than 7 days early
			            DeliveryDifference < 0,  "Early",               -- 1 to 7 days early
			            DeliveryDifference <= 7, "On Time",             -- Within 7 days late or on time
			            DeliveryDifference > 7,  "Late",                -- More than 7 days late
			            "Unknown"                                       -- Fallback for unexpected cases
			        ))
			```
		lineageTag: 9b2ccf09-1c30-404b-8029-411e5dae33b3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Order Status Group' = ```
			
			SWITCH(
			    TRUE(),
			    
			    -- DELIVERED: Check for the final successful status
			    'e-commerce orders'[order_status] = "delivered", "Delivered",
			    
			    -- CANCELED: Check for common cancellation/unavailability statuses
			    'e-commerce orders'[order_status] IN {"canceled"}, "Cancelled",
			    
			    -- OTHERS: Everything else that is still in process or pending
			    -- This includes: approved, created, invoiced, processing, shipped, etc.
			    TRUE(), "Others"
			)
			```
		lineageTag: 8e25fbef-6fcc-4067-8102-c82c38f13e8d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce orders' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_orders" = Source{[Schema="e-commerce",Item="orders"]}[Data]
				in
				    #"e-commerce_orders"

	annotation PBI_ResultType = Table

