table 'e-commerce order_reviews'
	lineageTag: bf749f1a-b293-4a5c-ae25-dd4d3bcf8f03

	measure 'Average Customer Ratings' =
			CALCULATE(
			    AVERAGE('e-commerce order_reviews'[review_score]))
		lineageTag: fc24dbfe-fcf7-4f91-9d64-d334c09edacd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Count of Bad Reviews' =
			
			CALCULATE(
			COUNT('e-commerce order_reviews'[review_score]),
			'e-commerce order_reviews'[review_score] <= 2)
		formatString: 0
		lineageTag: a8afad84-55bf-4607-a0ed-c055362a05b0

	column review_id
		dataType: string
		lineageTag: ce078a5e-72c7-41fa-ab1c-01c05e217362
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 0f81eff1-c7d1-4d6f-9d32-f82d4664c75f
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 3b9e55a9-29b4-4466-8a1c-fb2d3fd48aab
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 62c9dcc3-4a44-4072-a846-47a3d163004a
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: b4d71e64-8e28-4f35-85d6-a0080891e9ac
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1f1ab30a-411a-428f-af21-663eed0f07af
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 2778d371-8a78-447d-b8ff-3b28fa96b0c5
			defaultHierarchy: LocalDateTable_fd1ab3af-b5b2-4b1f-8681-3c394e74d816.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: ecaf1259-515a-4374-b10b-6af794b2e5f8
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: e4aa2391-2a83-4737-8599-e9754dc90eff
			defaultHierarchy: LocalDateTable_92d14681-3815-4775-8fac-6cfe4e31e665.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Review Sentiment Category' =
			
			IF(
			'e-commerce order_reviews'[review_score] <= 2,
			"Bad Review",
			"Good Review"
			)
		lineageTag: 92cfd36e-e58d-461a-85cd-9547181c65f8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce order_reviews' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_order_reviews" = Source{[Schema="e-commerce",Item="order_reviews"]}[Data]
				in
				    #"e-commerce_order_reviews"

	annotation PBI_ResultType = Table

