table 'e-commerce orders_per_day_of_the_week_and_hour'
	lineageTag: 69b81d30-a158-4ede-9f92-7ad38b9a4c7b

	column day_of_week_name
		dataType: string
		lineageTag: 09b431c6-dc98-45d3-ab87-71e5dea83452
		summarizeBy: none
		sourceColumn: day_of_week_name
		sortByColumn: Day_Sort_Order_CC

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 0
		dataType: int64
		formatString: 0
		lineageTag: 9bb05b93-f4e0-4f23-a6ca-688c8bbfb4ff
		summarizeBy: sum
		sourceColumn: 0

		annotation SummarizationSetBy = Automatic

	column 1
		dataType: int64
		formatString: 0
		lineageTag: ff802298-9f2c-4a63-acc6-aecc0ab5ffe5
		summarizeBy: sum
		sourceColumn: 1

		annotation SummarizationSetBy = Automatic

	column 2
		dataType: int64
		formatString: 0
		lineageTag: 296c5d87-bc72-4132-a047-b8e8fd3222da
		summarizeBy: sum
		sourceColumn: 2

		annotation SummarizationSetBy = Automatic

	column 3
		dataType: int64
		formatString: 0
		lineageTag: cdecea6b-ff08-44c1-8c16-998cd167a045
		summarizeBy: sum
		sourceColumn: 3

		annotation SummarizationSetBy = Automatic

	column 4
		dataType: int64
		formatString: 0
		lineageTag: 90001f10-52c8-463e-bead-9b3770d6ffca
		summarizeBy: sum
		sourceColumn: 4

		annotation SummarizationSetBy = Automatic

	column 5
		dataType: int64
		formatString: 0
		lineageTag: 6948dfb0-f056-4c38-836d-cf5d2ff126b9
		summarizeBy: sum
		sourceColumn: 5

		annotation SummarizationSetBy = Automatic

	column 6
		dataType: int64
		formatString: 0
		lineageTag: 5c3b07f1-cc53-47d2-8e33-e886980491b5
		summarizeBy: sum
		sourceColumn: 6

		annotation SummarizationSetBy = Automatic

	column 7
		dataType: int64
		formatString: 0
		lineageTag: fbbe61f4-a85e-467d-ad17-2a762376401e
		summarizeBy: sum
		sourceColumn: 7

		annotation SummarizationSetBy = Automatic

	column 8
		dataType: int64
		formatString: 0
		lineageTag: bb4014b4-d914-4d22-ac44-b46df1b0cd0a
		summarizeBy: sum
		sourceColumn: 8

		annotation SummarizationSetBy = Automatic

	column 9
		dataType: int64
		formatString: 0
		lineageTag: 3d790a95-1828-450b-866c-0e365ab104bd
		summarizeBy: sum
		sourceColumn: 9

		annotation SummarizationSetBy = Automatic

	column 10
		dataType: int64
		formatString: 0
		lineageTag: bfaada3e-164c-40b3-93d4-15479350f863
		summarizeBy: sum
		sourceColumn: 10

		annotation SummarizationSetBy = Automatic

	column 11
		dataType: int64
		formatString: 0
		lineageTag: 66821e6f-190d-4331-95ca-700c3673cdb6
		summarizeBy: sum
		sourceColumn: 11

		annotation SummarizationSetBy = Automatic

	column 12
		dataType: int64
		formatString: 0
		lineageTag: af88421e-3c69-4f87-9460-27fb178786c1
		summarizeBy: sum
		sourceColumn: 12

		annotation SummarizationSetBy = Automatic

	column 13
		dataType: int64
		formatString: 0
		lineageTag: 3622dbe0-b813-41a5-8ea6-fcf2c6f525eb
		summarizeBy: sum
		sourceColumn: 13

		annotation SummarizationSetBy = Automatic

	column 14
		dataType: int64
		formatString: 0
		lineageTag: 4f66f8ef-2ab7-4a8a-81e8-ff66e4b0102a
		summarizeBy: sum
		sourceColumn: 14

		annotation SummarizationSetBy = Automatic

	column 15
		dataType: int64
		formatString: 0
		lineageTag: c7f28392-250d-4fa8-83bd-b2f6b09ed6de
		summarizeBy: sum
		sourceColumn: 15

		annotation SummarizationSetBy = Automatic

	column 16
		dataType: int64
		formatString: 0
		lineageTag: 3771bfa3-185c-45c9-b43d-a8db4b4d2c1b
		summarizeBy: sum
		sourceColumn: 16

		annotation SummarizationSetBy = Automatic

	column 17
		dataType: int64
		formatString: 0
		lineageTag: 6ce06e2c-c094-41ac-99f5-ab98e5d6b505
		summarizeBy: sum
		sourceColumn: 17

		annotation SummarizationSetBy = Automatic

	column 18
		dataType: int64
		formatString: 0
		lineageTag: 6fa27c4e-bd64-4eec-a64a-15118d76bcc8
		summarizeBy: sum
		sourceColumn: 18

		annotation SummarizationSetBy = Automatic

	column 19
		dataType: int64
		formatString: 0
		lineageTag: 4c93d114-843c-4a3a-9d9c-3f20e12282bc
		summarizeBy: sum
		sourceColumn: 19

		annotation SummarizationSetBy = Automatic

	column 20
		dataType: int64
		formatString: 0
		lineageTag: 91416930-e4eb-409b-923e-6b97bd83487f
		summarizeBy: sum
		sourceColumn: 20

		annotation SummarizationSetBy = Automatic

	column 21
		dataType: int64
		formatString: 0
		lineageTag: ba2f638e-da68-4b09-bb0f-282501d7cadc
		summarizeBy: sum
		sourceColumn: 21

		annotation SummarizationSetBy = Automatic

	column 22
		dataType: int64
		formatString: 0
		lineageTag: d0d21a40-5bfc-456e-8e99-053e838b1eec
		summarizeBy: sum
		sourceColumn: 22

		annotation SummarizationSetBy = Automatic

	column 23
		dataType: int64
		formatString: 0
		lineageTag: fd352f87-f99b-445d-ae03-0b3a65fe1bb0
		summarizeBy: sum
		sourceColumn: 23

		annotation SummarizationSetBy = Automatic

	column Day_Sort_Order =
			SWITCH(
			    'e-commerce orders_per_day_of_the_week_and_hour'[day_of_week_name],
			    "Sun", 1,
			    "Mon", 2,
			    "Tue", 3,
			    "Wed", 4,
			    "Thu", 5,
			    "Fri", 6,
			    "Sat", 7
			)
		formatString: 0
		lineageTag: badb35d0-9cd4-4e2a-aa17-bdf84ac1b434
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Day_Sort_Order_CC
		dataType: string
		lineageTag: 359052b2-7fa2-4aaf-b782-c9257aacf08c
		summarizeBy: none
		sourceColumn: Day_Sort_Order_CC

		annotation SummarizationSetBy = Automatic

	column 'Total Daily Value' = ```
			
			    'e-commerce orders_per_day_of_the_week_and_hour'[0] + 'e-commerce orders_per_day_of_the_week_and_hour'[1] + 'e-commerce orders_per_day_of_the_week_and_hour'[2] + 'e-commerce orders_per_day_of_the_week_and_hour'[3] + 'e-commerce orders_per_day_of_the_week_and_hour'[4] + 'e-commerce orders_per_day_of_the_week_and_hour'[5] + 'e-commerce orders_per_day_of_the_week_and_hour'[6] + 'e-commerce orders_per_day_of_the_week_and_hour'[7] +'e-commerce orders_per_day_of_the_week_and_hour'[8] + 'e-commerce orders_per_day_of_the_week_and_hour'[9] +'e-commerce orders_per_day_of_the_week_and_hour'[10] + 'e-commerce orders_per_day_of_the_week_and_hour'[11] + 'e-commerce orders_per_day_of_the_week_and_hour'[12] + 'e-commerce orders_per_day_of_the_week_and_hour'[13] + 'e-commerce orders_per_day_of_the_week_and_hour'[14] + 'e-commerce orders_per_day_of_the_week_and_hour'[15] + 'e-commerce orders_per_day_of_the_week_and_hour'[16] + 'e-commerce orders_per_day_of_the_week_and_hour'[17] + 'e-commerce orders_per_day_of_the_week_and_hour'[18] + 'e-commerce orders_per_day_of_the_week_and_hour'[19] + 'e-commerce orders_per_day_of_the_week_and_hour'[20] + 'e-commerce orders_per_day_of_the_week_and_hour'[21] + 'e-commerce orders_per_day_of_the_week_and_hour'[22] + 'e-commerce orders_per_day_of_the_week_and_hour'[23]
			```
		formatString: 0
		lineageTag: 4dbd9f42-f6ef-415c-8978-aedaec275d34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'e-commerce orders_per_day_of_the_week_and_hour' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "e-commerce", [ReturnSingleDatabase=true]),
				    #"e-commerce_orders_per_day_of_the_week_and_hour" = Source{[Schema="e-commerce",Item="orders_per_day_of_the_week_and_hour"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(#"e-commerce_orders_per_day_of_the_week_and_hour", "Day_Sort_Order_CC", each if [day_of_week_name] = "Sun" then 1 else if [day_of_week_name] = "Mon" then 2 else if [day_of_week_name] = "Tue" then 3 else if [day_of_week_name] = "Wed" then 4 else if [day_of_week_name] = "Thu" then 5 else if [day_of_week_name] = "Fri" then 6 else if [day_of_week_name] = "Sat" then 7 else null)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

