table 'Top Products'
	lineageTag: 09d3630f-4918-40e8-b81f-41226862296a

	measure 'Top Products Value' = SELECTEDVALUE('Top Products'[Top Products], 50)
		formatString: 0
		lineageTag: 0eedca39-6f56-4238-bac1-cdc3cb01984e

	measure 'Display Status' =
			
			VAR TopNProductCategories =
			    -- Get a list of the Top N product categories by GMV
			    TOPN([Top Products Value],
			        ALL( 'e-commerce product_category_name_translation'[product_category_name_english]),
			        CALCULATE(SUM('e-commerce order_values_payments'[gmv]) ),
			        DESC
			    )
			VAR SelectedCategory =
			    -- Get the single selected category name
			    SELECTEDVALUE ( 'e-commerce product_category_name_translation'[product_category_name_english] )
			RETURN
			    -- Check if a single category is selected AND that category is in the Top N list
			    IF(
			        NOT ISBLANK(SelectedCategory) &&
			        SelectedCategory IN TopNProductCategories,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 43374a8e-5e55-42ab-ae7a-d855ce1f3617

	measure 'Selected N Value' = SELECTEDVALUE('Top Products'[Top Products])
		formatString: 0
		lineageTag: f640e508-f613-4dca-9e8d-e193a47ac561

	measure 'Top N% GMV Contribution' =
			
			// 1. Define N using the existing measure that retrieves the selected value from a slicer/parameter.
			VAR N_Categories = [Selected N Value]
			
			// 2. Calculate the total GMV across the entire data model, ignoring all filters.
			VAR TotalGMV =
			    CALCULATE(
			        SUM('e-commerce order_values_payments'[gmv]),
			        ALL('e-commerce product_category_name_translation') // Important: Use ALL on the dimension table.
			    )
			
			// 3. Calculate the GMV only for the Top N product categories.
			VAR TopNCategoriesGMV =
			    CALCULATE(
			        SUM('e-commerce order_values_payments'[gmv]),
			        // TOPN creates a table of the top N categories based on their GMV, using the dynamic N_Categories variable.
			        TOPN(
			            N_Categories,
			            // We use ALL to ensure we are ranking against ALL categories, not just the currently filtered ones.
			            ALL('e-commerce product_category_name_translation'[product_category_name_english]),
			            // The value used for ranking/ordering
			            CALCULATE(SUM('e-commerce order_values_payments'[gmv])),
			            DESC
			        )
			    )
			
			// 4. Divide the Top N GMV by the Total GMV to get the percentage contribution.
			RETURN
			    DIVIDE(TopNCategoriesGMV, TotalGMV, 0)
		lineageTag: 4ba4c786-1f32-4bc2-958e-604fed4dc4ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top N GMV Value' = ```
			
			// 1. Define N using the existing measure that retrieves the selected value from a slicer/parameter.
			VAR N_Categories = [Selected N Value]
			
			// 2. Calculate the GMV only for the Top N product categories.
			VAR TopNCategoriesGMV =
			    CALCULATE(
			        SUM('e-commerce order_values_payments'[gmv]),
			        // Determine the Top N categories
			        TOPN(
			            N_Categories,
			            ALL('e-commerce product_category_name_translation'[product_category_name_english]),
			            CALCULATE(SUM('e-commerce order_values_payments'[gmv])),
			            DESC
			        )
			    )
			
			// 3. Return only the numerical value for the Top N GMV.
			// Apply desired formatting (e.g., currency) in the Power BI visual settings.
			RETURN
			    TopNCategoriesGMV
			    
			```
		lineageTag: 310b20d2-dd73-443e-a8aa-de7b3858d370

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalGMV = ```
			CALCULATE(
			    SUM('e-commerce order_values_payments'[gmv]), 
			    ALL('e-commerce product_category_name_translation'))
			```
		lineageTag: 579c8aba-ea13-4035-96f5-81f98e651f83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Products'
		formatString: 0
		lineageTag: 79ba417d-d180-4f99-a682-361c0efad014
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Top Products' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_Id = 27e04fd8f48b4090863cdcc56a196236

